###
POST {{ url }}/api/ping/
Accept: */*
Cache-Control: no-cache
Authorization: Token {{token}}

{
  "name": "TEST.Node1"
}

###

POST {{ url }}/api/goods/
Authorization: Token {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "TestGoods",
  "cost": "0.1",
  "query_link": "a0db6793-52e2-4705-97e1-8664a6fa3601",
  "external_id": "http://get.com/45",
  "goods_url": "http://get.com/5"

}

###
GET {{ url }}/api/token?name=CGBot.Node.Avito
Accept: application/json
Authorization: Token {{token}}

###
GET {{ url }}/api/link?name=Test.Node
Accept: application/json
Authorization: Token {{token}}

