kind: pipeline
type: exec
name: AdNotify.Manager

platform:
  os: linux
  arch: amd64

steps:
- name: setup env
  environment:
    TELEGRAM_BOT:
      from_secret: TELEGRAM_BOT
  commands:
  - sed -i 's/TELEGRAM_BOT=YOUR_TELEGRAM_TOKEN//g' .env.example ;
  - echo TELEGRAM_BOT=$TELEGRAM_BOT >> .env.example ;
  - sed -i 's/CSRF_COOKIE_DOMAIN=CSRF_COOKIE_DOMAIN//g' .env.example ;
  - echo CSRF_COOKIE_DOMAIN=*.cg-bot.ru >> .env.example ;
  - sed -i 's/CSRF_TRUSTED_ORIGINS=\[\]//g' .env.example ;
  - echo CSRF_TRUSTED_ORIGINS=[\'https://adnotify.cg-bot.ru\'] >> .env.example ;
  - cp .env.example .env.prod ;
  - cat .env.prod


- name: build and run
  commands:
  - docker-compose -f docker-compose.yml up -d --build ;

