kind: pipeline
type: exec
name: AdNotify.Manager

platform:
  os: linux
  arch: amd64

steps:
- name: setup env
  environment:
    TELEGRAM_BOT:
      from_secret: TELEGRAM_BOT
  commands:
  - sed -i 's/TELEGRAM_BOT=YOUR_TELEGRAM_TOKEN//g' .env.example ;
  - echo TELEGRAM_BOT=$TELEGRAM_BOT >> .env.example ;
  - sed -i 's/CSRF_COOKIE_DOMAIN=CSRF_COOKIE_DOMAIN//g' .env.example ;
  - echo CSRF_COOKIE_DOMAIN=*.cg-bot.ru >> .env.example ;
  - sed -i 's/CSRF_TRUSTED_ORIGINS=YOUR_DOMAIN//g' .env.example ;
  - echo CSRF_TRUSTED_ORIGINS=https://adnotify.cg-bot.ru >> .env.example ;
  - sed -i 's/CORS_ORIGIN_WHITELIST=YOUR_DOMAIN//g' .env.example ;
  - echo CORS_ORIGIN_WHITELIST=\'https://adnotify.cg-bot.ru\' >> .env.example ;
  - cp .env.example .env.prod ;
  - cat .env.prod

- name: setup env node
  environment:
    API_KEY:
      from_secret: NODE.API_KEY
    PROVIDER_API_KEY:
      from_secret: NODE.PROVIDER_API_KEY
    PROVIDER_API_URL:
      from_secret: NODE.PROVIDER_API_URL

  commands:
    - sed -i 's/API_URL=API_URL/API_URL=https:\/\/adnotify.cg-bot.ru\//g' .env.example ;
    - sed -i 's/NAME=NAME/CG.Node.Avito/g' .env.example ;
    - sed -i 's/PROVIDER=LOCAL/PROVIDER=COMMUNICATOR/g' .env.example ;
    - echo PROVIDER_API_KEY=PROVIDER_API_KEY >> .env.example ;
    - echo PROVIDER_API_URL=PROVIDER_API_URL >> .env.example ;
    - echo API_KEY=API_KEY >> .env.example ;
    - cp .env.node.example .env.node.prod ;
    - cat .env.node.prod

- name: build and run
  commands:
  - docker-compose -f docker-compose.yml up -d --build ;

