kind: pipeline
type: exec
name: AdNotify.Manager

platform:
  os: linux
  arch: amd64

steps:
- name: setup env
  environment:
    TELEGRAM_BOT:
      from_secret: TELEGRAM_BOT
    commands:
    - sed -i 's/YOUR_TELEGRAM_TOKEN/$TELEGRAM_BOT/g' .env.example
    - cp .env.example .env.prod


- name: build and run
  commands:
    - docker-compose -f docker-compose.yml up -d --build

