version: "3.7"

services:
  web:
    container_name: AdNotifyManager
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - staticfiles:/app/staticfiles
      - db:/app/db
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod

volumes:
  staticfiles:
  db: