# Generated by Django 4.0 on 2022-01-22 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('last_connect', models.DateTimeField(blank=True, null=True)),
                ('count_request', models.IntegerField(default=0)),
                ('count_request_error', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='QueryLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_create', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 23, 42, 747468))),
                ('data_expired', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 15, 23, 42, 747468), null=True)),
                ('query_link_type', models.IntegerField(choices=[(0, 'Base'), (1, 'Avito')], default=0)),
                ('url', models.CharField(max_length=300)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdNotifyManager.node')),
            ],
            options={
                'ordering': ['-data_create'],
            },
        ),
    ]
