# Generated by Django 4.0 on 2022-01-22 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdNotifyManager', '0007_querylink_filter_locate_alter_querylink_data_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylink',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 41, 6, 956582)),
        ),
        migrations.AlterField(
            model_name='querylink',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 15, 41, 6, 956582), null=True),
        ),
    ]
