# Generated by Django 4.0 on 2022-01-22 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AdNotifyManager', '0008_alter_querylink_data_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylink',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 50, 30, 849800)),
        ),
        migrations.AlterField(
            model_name='querylink',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 15, 50, 30, 849800), null=True),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_create', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 50, 30, 853723))),
                ('data_expired', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 15, 50, 30, 853723), null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('channel_id', models.CharField(blank=True, max_length=50)),
                ('subscriber_channel_type', models.IntegerField(blank=True, choices=[(1, 'Telegram')], default=1, null=True)),
                ('query_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdNotifyManager.querylink')),
            ],
        ),
    ]
