# Generated by Django 4.0 on 2022-01-22 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdNotifyManager', '0009_alter_querylink_data_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylink',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 50, 33, 683206)),
        ),
        migrations.AlterField(
            model_name='querylink',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 15, 50, 33, 683206), null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 50, 33, 684247)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 15, 50, 33, 684247), null=True),
        ),
    ]
