# Generated by Django 4.0 on 2022-01-22 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdNotifyManager', '0012_alter_querylink_data_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Goods', 'verbose_name_plural': 'Goods'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='success',
        ),
        migrations.AlterField(
            model_name='querylink',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 21, 41, 4, 943511)),
        ),
        migrations.AlterField(
            model_name='querylink',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 21, 41, 4, 943511), null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 21, 41, 4, 945507)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 21, 41, 4, 945507), null=True),
        ),
    ]
