# Generated by Django 4.0 on 2022-01-22 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdNotifyManager', '0013_alter_goods_options_remove_goods_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylink',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 21, 41, 8, 1919)),
        ),
        migrations.AlterField(
            model_name='querylink',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 21, 41, 8, 1919), null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 21, 41, 8, 4934)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='data_expired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 21, 41, 8, 4934), null=True),
        ),
    ]
