# Generated by Django 4.0.1 on 2022-01-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdNotifyManager', '0016_alter_goods_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylink',
            name='filter_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
